### PR TITLE
[WIP] Added placeholder of blog post on Load Testing With RxJS

### PR DESCRIPTION
**Pull request by deanius**
Hey y'all - this is spawned off a [Gist](https://gist.github.com/deanius/6284d7b8d634b6f0bb8ae28a063a21a1#file-loadtest-js) I made that people in RxJS land liked. Thought you might like something like this in your blog. Puns on agents and doubling down aplenty are possible. Let me know where you'd like to take it, if anywhere, I left some TODOs as to what I could develop. It's being used to test a WebSocket based solution for which existing tools were really sparse, and the find-vs-make tradeoff was heavily in favor of making.

### CODE REVIEW

**Comment by deanius** [comment]
Would love some help finishin' up this week if you guys want it!

**Comment by deanius** [comment]
One possibility is i make the requesting code (getAgentTask) more generic, such as a promise returned by fetch. That's the only requirement of getAgebtTask

**Comment by searls** [comment]
Hey Dean, I'm sort of blown away by the generosity that you'd write a blog post for the td blog after your tenure here! I reflected on this a bit last night and I feel like we should keep the blog as a platform for the thoughts & learnings of agents as they're currently serving. 

My thinking is that the blog is intended as a reflection of the work our agency has done and is currently doing/building/learning/thinking and serves a number of purposes, including as a bit of an entree to prospective clients about what the people at Test Double are like. As a result, having people write to the blog (especially fabulous people with really smart content like yourself) but who aren't currently representing Test Double seems a little disingenuous on this front. To illustrate, if I was a prospective client perusing the company blog, I'd feel a little baited-and-switched that the author didn't even work at the company at the time.

I hope you'll understand this thinking and I'm always happy to speak privately (besides, it'd be good to catch up!), and wherever you do end up posting this article, I'll be glad to tweet/share it along, too.

**Comment by deanius** [comment]
Once an agent, always a (sleeper) agent. 🤘

**Comment by searls** [comment]
🤐!

**Pull request closed without merging**
