### PR TITLE
Add Wat's Going On? post.

### PR DESCRIPTION
**Pull request by Schoonology**
A couple specific points of feedback I'd like:

- The canonical reference. It supposedly keeps Google from punishing either site for duplicate content, but I'm no SEO Expert™.
- The non-metadata Wistia embed.

### CODE REVIEW

**Comment by searls** [comment]
In the interest of #branding, I'd prefer to de-emphasize when content is cross-posted to people's personal blogs. Could you move it to the bottom?

**Comment by searls** [comment]
Haven't had a chance to watch the video yet but the splash looks great, so does the burn-your-eyes-but-on-brand green player controls :+1:

**Comment by Schoonology** [comment]
Interestingly, that green is _not_ the TD green; it's the green my website uses. :smile:

T minus one minute on pushing the updated canonical link.

**Comment by searls** [comment]
Thanks Schoon

**Comment by deanius** [comment]
Nice production values Schoon ! Were you reading off your teleprompter app?

**Comment by deanius** [comment]
OMG ROFL your post about online calls IRL https://www.youtube.com/watch?v=DYu_bGbZiiQ

**Comment by Schoonology** [comment]
Good catch with the 404s. Now I know what I'm fixing tonight...

I _was_ reading from a teleprompter of sorts, but it was the day I thought to build said app. Instead, we hacked together an _amazing_ teleprompter with my laptop on a toolbox on a stool on a box on the floor, balanced by a sandbag... it was _perfect_.

**Comment by Schoonology** [comment]
Also, there should be a picture on Slack under #marketing.

**Comment by jasonkarns** [comment]
@Schoonology merged #67 into #61

**Comment by Schoonology** [comment]
Looks good to me. Who else needs to chime in for consensus/quorum?

**Comment by jasonkarns** [comment]
Last post was published on Monday so it's had almost a week on the homepage. So I'd say you're good to merge whenever you like. Monday might be better for traffic, but anytime is fine.

**Pull request merged**
