### PR TITLE
Open Source Spotlight: Dependable

### PR DESCRIPTION
**Pull request by davemo**

### CODE REVIEW

**Comment by samjonester** [comment]
I like the messaging around the open source that TD is involved in, but I'm not sure I like that it opens the article. It pushes the purpose of the article (you did awesome things with dependable) below the fold. It also doesn't grab my attention very well.

**Comment by davemo** [comment]
Agreed @samjonester, I've removed the opening portions and left this blog post simply to focus on dependable. We'll revisit the removed content in the upcoming testdouble.com/opensource page :)

**Comment by davemo** [comment]
Ah, this reminds me I need to restore our table formatting :)

**Comment by searls** [comment]
IIRC, our old table formatting was atrocious. Would recommend taking a stab at new sass for it in base/components/table.sass

**Pull request closed without merging**
