### PR TITLE
Add Restoring Sanity with Ember 2 post

### PR DESCRIPTION
**Pull request by kpfefferle**

### CODE REVIEW

**Comment by searls** [comment]
looks good! so that we can pace things out and give @neall some time to shine, what do you say we shoot to merge this in around 11am eastern on monday or tuesday?

**Comment by searls** [comment]
only feedback is that the large abstract block quote looks a little jarring, esp. since it isn't called out. i think it'd maybe look better if you just shortened it up in your own words and let the talk speak for itself.

**Comment by kpfefferle** [comment]
I opened the PR instead of merging right away so we could figure out a good timing for publishing. Early next week is fine with me 👍

I also changed the blockquote abstract to a normal paragraph and removed the last part about "you'll leave this session with...". I like the rest of the abstract for explaining the purpose of the content.

**Comment by searls** [comment]
Cool beans, @kpfefferle. Keep in mind (it's not readily apparent to everyone) that as soon as anything hits master on github it gets deployed to heroku

**Pull request merged**
