### PR TITLE
Add sledgehammer blog post

### PR DESCRIPTION
**Pull request by kbaribeau**

### CODE REVIEW

**Comment by Schoonology** [comment]
@kbaribeau This looks great.

**Comment by McPolemic** [comment]
@kbaribeau I like this a lot. It's kind of a manual rebase 😄. 

I think you may want to spend a little more time explaining how to abort the sledgehammer mid-process. You mention using `git reset -hard` for your target branch and master and that git hasn't lost those commits, but not really how to get back to your target branch if you want to abort. I could see a situation where they get halfway through cherry-picking commits and want to start over or abort the process, so they `git reset --hard <your-branch-name>` only to find out that they can't get back. `git checkout <your-branch-name`. Etc. Without knowing they can reset to a particular SHA, origin branch, or the reflog, it could feel like they've lost data.

If you wanted to stay away from explaining `git reset`, another method would be to check out a new branch based on master and cherry-pick from there. This might be a bit more amenable to your audience as they always have their original branch until they're confident that they have everything merged properly. 

Something like:
```
git checkout -b my-merge-branch <target-branch-name>

# Get list of SHAs, same as before
git log --format=oneline master..<target-branch-name>

# git cherry-pick in order as before

# Looks good, let's force-rename the branch
git branch -M <target-branch-name>
```

**Comment by kbaribeau** [comment]
@McPolemic You definitely have a point. I like the simplicity of this approach though. I think it has a little more appeal this way. It's also an easier lesson.

I'd like to include a reference to the reflog, but I can't find a way to sneak it in that I like.

**Comment by searls** [comment]
I support any blog post that leads with "You're paralyzed with fear and cannot continue."

**Pull request merged**
