### PR TITLE
Update 2015-02-16-arcane-knowledge.md

### PR DESCRIPTION
**Pull request by jasonkarns**
Notes from feedback 

https://github.com/testdouble/feedback/issues/2
https://github.com/testdouble/feedback/issues/3

### CODE REVIEW

**Comment by searls** [comment]
I didn't add that step for lack of knowing minitest is in stdlib; despite that fact, I've always run into errors using minitest in Rails without the gem in my Gemfile, and that's why I had to add it to this case. I'd be okay with an aside statement ("despite it being in stdlib")

**Comment by searls** [comment]
The other update is not accurate either. You can use bundler caching in public repositories, using travis's container architecture: https://docs.travis-ci.com/user/workers/container-based-infrastructure/

**Comment by searls** [comment]
Recommend closing

**Comment by jasonkarns** [comment]
Was the travis container infrastructure even a thing in Feb 2015? Are public caches with the container infrastructure a new thing since then?

**Comment by searls** [comment]
Why does it matter? Doesn't make sense to update it now to say it doesn't.

**Pull request closed without merging**
