### PR TITLE
Add "Solving the Boolean Identity Crisis" talk

### PR DESCRIPTION
**Pull request by jfairbank**

### CODE REVIEW

**Comment by searls** [comment]
Only feedback: both sub-headers use "I" language to describe what you talk about, but I think it's a little more inviting when that's implied and instead the headers state what the viewer would get out about it. Even if that results in really short headers like "The problems with booleans"

**Comment by jfairbank** [comment]
@searls Thanks for the feedback! I made some tweaks to the sub-headers and the opening paragraph.

**Comment by searls** [comment]
LGTM

**Comment by jordanwilcken** [comment]
Going to share the Youtube video with the fellows at work.

You make a really solid case for being measured in the use of booleans.  You also make a compelling case for using types to promote correctness.  It really is nice when the compiler makes impossible states impossible.

**Pull request merged**
