### PR TITLE
Isomorphic ClojureScript with Reagent and Node.js

### PR DESCRIPTION
**Pull request by andrewvida**
Blog covering the one demo that I didn't get to in my CodeMash presentation.

@searls Feel free to queue this up whenever, since we now have a backlog of posts!

### CODE REVIEW

**Comment by searls** [comment]
woah! didn't see this coming

**Comment by searls** [comment]
weirdly, the review app isn't working. it's pointing to neal's. huh

**Comment by searls** [comment]
@andrewvida i propose you merge this in midday next thursday at your leisure.

@bostonaholic / @kbaribeau any chance you could give this a review? Clojure/Script is still greek to me, I'm afraid :dizzy_face:

**Comment by andrewvida** [comment]
@kbaribeau :+1:

**Pull request merged**
